import { useAuth } from "@/_core/hooks/useAuth";
import EditorialDashboard from "@/components/EditorialDashboard";
import DashboardLayout from "@/components/DashboardLayout";
import { startLogin } from "@/const";
import { Button } from "@/components/ui/button";
import { Loader2, LockKeyhole, ShieldAlert } from "lucide-react";

export default function Editorial() { const { user, loading } = useAuth(); if (loading) return <div className="grid min-h-screen place-items-center bg-[#f8f4ea]"><Loader2 className="animate-spin text-[#743a3d]" aria-label="Verificando acesso" /></div>; if (!user) return <AccessCard icon={<LockKeyhole />} eyebrow="Área restrita" title="Redação da Tribuna Jovem" text="Entre com a conta aprovada pela equipe responsável para acessar, revisar e publicar materiais." action="Entrar na redação" onClick={() => startLogin()} />; if (user.role !== "admin") return <AccessCard icon={<ShieldAlert />} eyebrow="Acesso aguardando aprovação" title="Sua conta ainda não faz parte da redação." text="Você fez login, mas a publicação é reservada a integrantes aprovados. Peça à pessoa responsável pelo jornal para autorizar sua conta." action="Voltar ao jornal" onClick={() => window.location.assign("/")} />; return <DashboardLayout><EditorialDashboard /></DashboardLayout>; }
function AccessCard({ icon, eyebrow, title, text, action, onClick }: { icon: React.ReactNode; eyebrow: string; title: string; text: string; action: string; onClick: () => void }) { return <main className="grid min-h-screen place-items-center bg-[#f8f4ea] p-5"><section className="w-full max-w-xl border border-[#73574788] bg-[#fdfaf3] p-7 sm:p-10"><span className="text-[#743a3d]">{icon}</span><p className="editorial-kicker mt-7 text-[#743a3d]">{eyebrow}</p><h1 className="editorial-title mt-2 text-4xl font-bold leading-tight">{title}</h1><p className="mt-5 text-sm leading-7 text-[#5c4b43]">{text}</p><Button className="mt-8" onClick={onClick}>{action}</Button></section></main>; }
