import { PublicPage } from "@/components/SiteHeader";
import { trpc } from "@/lib/trpc";
import { ArrowUpRight, FileText, Loader2, Search, X } from "lucide-react";
import { useMemo, useState } from "react";

export default function Editions() {
  const { data, isLoading, error } = trpc.editorial.public.editions.useQuery();
  const [query, setQuery] = useState("");
  const matchingEditions = useMemo(() => {
    const normalized = query.trim().toLocaleLowerCase("pt-BR");
    if (!normalized) return data ?? [];
    return (data ?? []).filter(edition => [edition.title, edition.issueLabel, edition.description].some(value => value.toLocaleLowerCase("pt-BR").includes(normalized)));
  }, [data, query]);
  return <PublicPage><PageIntro eyebrow="Arquivo público" title="Edições do jornal" text="Cada edição reúne leituras, pesquisas e produções que ajudam a comunidade escolar a refletir sobre dignidade, respeito e direitos." /><section className="mx-auto max-w-7xl px-5 pb-20 lg:px-8">{isLoading ? <Loading /> : error ? <ErrorMessage /> : data?.length ? <><div className="mb-8 flex flex-col justify-between gap-4 border-y border-[#73574766] py-4 sm:flex-row sm:items-center"><label className="relative block max-w-md flex-1"><span className="sr-only">Buscar edição</span><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[#743a3d]" size={18} /><input className="editorial-input pl-10 pr-10" value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar por título, edição ou tema" /></label><div className="flex items-center gap-4"><p className="editorial-kicker text-[#745d4d]">{matchingEditions.length} de {data.length} edições</p>{query && <button type="button" className="inline-flex items-center gap-1 text-xs font-bold text-[#743a3d] underline underline-offset-4" onClick={() => setQuery("")}><X size={14} /> Limpar</button>}</div></div>{matchingEditions.length ? <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{matchingEditions.map((edition, index) => <article key={edition.id} className="editorial-card flex min-h-80 flex-col justify-between p-6"><div><p className="editorial-kicker text-[#743a3d]">{edition.issueLabel}</p><span className="editorial-title mt-9 block text-7xl leading-none text-[#c49f68]">{String(index + 1).padStart(2, "0")}</span><h2 className="editorial-title mt-4 text-4xl font-bold leading-tight">{edition.title}</h2><p className="mt-4 text-sm leading-6 text-[#5c4b43]">{edition.description}</p></div>{edition.documentUrl ? <a className="mt-7 inline-flex items-center justify-between border-t border-[#73574788] pt-4 text-sm font-bold" href={edition.documentUrl} target="_blank" rel="noreferrer">Ler PDF <ArrowUpRight size={18} /></a> : <p className="mt-7 border-t border-[#73574788] pt-4 text-sm text-[#6b584b]">Arquivo em preparação</p>}</article>)}</div> : <Empty title="Nenhuma edição encontrada." text={`Não localizamos publicações para “${query}”. Tente um termo mais amplo ou limpe a busca para ver todo o arquivo.`} />}</> : <Empty title="O arquivo do jornal está começando." text="As edições publicadas pela redação aparecerão aqui com seus respectivos links de leitura." />}</section></PublicPage>;
}

export function PageIntro({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <section className="mx-auto max-w-7xl px-5 pb-12 pt-16 lg:px-8 lg:pb-16 lg:pt-20"><p className="editorial-kicker text-[#743a3d]">{eyebrow}</p><div className="mt-4 grid gap-7 border-t border-[#73574788] pt-5 lg:grid-cols-[1.15fr_0.85fr]"><h1 className="editorial-title text-5xl font-bold leading-[0.93] sm:text-7xl">{title}</h1><p className="max-w-xl self-end text-base leading-7 text-[#5c4b43]">{text}</p></div></section>; }
export function Loading() { return <div className="grid min-h-56 place-items-center"><Loader2 className="animate-spin text-[#743a3d]" aria-label="Carregando" /></div>; }
export function ErrorMessage() { return <div role="alert" className="border-l-4 border-[#743a3d] bg-[#f1e3d1] p-6 text-sm leading-6 text-[#5c4b43]">Não foi possível carregar o conteúdo agora. Atualize a página em alguns instantes.</div>; }
export function Empty({ title, text }: { title: string; text: string }) { return <div className="border border-dashed border-[#73574788] p-8 sm:p-12"><FileText className="size-8 text-[#743a3d]" /><h2 className="editorial-title mt-5 text-4xl font-bold">{title}</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-[#5c4b43]">{text}</p></div>; }
